### ISSUE TITLE
Incompatible with Tasks 

### ISSUE THREAD

**Issue by ma-sadeghi** [mwxgaf/obsidian-dynamic-rtl#22]
How to reproduce:

```
```tasks
tag includes test
hide backlink
hide edit button
```

- [ ] Test #test
- [ ] Another test #test 
- [ ] Yet another test #test 
- [ ] 

![image](https://user-images.githubusercontent.com/14086031/230701115-95197d6a-e00c-4fbc-a26f-35f27fd8d734.png)

**Comment by ma-sadeghi** [comment]
Any update on this? Thanks :-)

**Comment by ma-sadeghi** [comment]
Here's a quick fix:

Add the following CSS rule to your custom CSS file:

```css
li.task-list-item.plugin-tasks-list-item > span > span > span > div {
    display: inline;
}
```
